# Generated by Django 4.0.1 on 2022-05-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uptated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
